name: generate animation
on:
  schedule:
    - cron: "0 */24 * * *"  # Fixed the syntax (added missing asterisk)
  workflow_dispatch:
  push:
    branches:
      - master
      - main  # Added in case you use main branch
jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # First checkout the repository so we can access files
      - name: Checkout
        uses: actions/checkout@v3

      # Generate snake SVGs using your existing configuration
      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Create directory for the new file if it doesn't exist
      - name: Create directory
        run: mkdir -p dist

      # Create custom Hussein Bakr contribution animation
      - name: Create custom animation
        run: |
          cat > dist/hussein-contribution-animation.svg << 'EOF'
          <svg width="900" height="200" xmlns="http://www.w3.org/2000/svg">
            <style>
              .cell { width: 15px; height: 15px; rx: 2px; ry: 2px; }
              .cell-0 { fill: #161b22; }
              .cell-1 { fill: #0e4429; }
              .cell-2 { fill: #006d32; }
              .cell-3 { fill: #26a641; }
              .cell-4 { fill: #39d353; }
              .worm { fill: #8b00ff; animation: move 10s infinite; }
              
              @keyframes move {
                0%, 100% { transform: translate(0, 0); }
                10% { transform: translate(15px, 15px); }
                20% { transform: translate(30px, 0); }
                30% { transform: translate(45px, 15px); }
                40% { transform: translate(60px, 0); }
                50% { transform: translate(75px, 15px); }
                60% { transform: translate(90px, 0); }
                70% { transform: translate(105px, 15px); }
                80% { transform: translate(120px, 0); }
                90% { transform: translate(135px, 15px); }
              }
            </style>
            
            <g transform="translate(10, 20)">
              <!-- H -->
              <rect class="cell cell-4" x="0" y="0" width="15" height="15" />
              <rect class="cell cell-4" x="60" y="0" width="15" height="15" />
              <rect class="cell cell-3" x="0" y="17" width="15" height="15" />
              <rect class="cell cell-3" x="60" y="17" width="15" height="15" />
              <rect class="cell cell-2" x="0" y="34" width="15" height="15" />
              <rect class="cell cell-2" x="15" y="34" width="15" height="15" />
              <rect class="cell cell-2" x="30" y="34" width="15" height="15" />
              <rect class="cell cell-2" x="45" y="34" width="15" height="15" />
              <rect class="cell cell-2" x="60" y="34" width="15" height="15" />
              <rect class="cell cell-1" x="0" y="51" width="15" height="15" />
              <rect class="cell cell-1" x="60" y="51" width="15" height="15" />
              <rect class="cell cell-1" x="0" y="68" width="15" height="15" />
              <rect class="cell cell-1" x="60" y="68" width="15" height="15" />
              
              <!-- u -->
              <rect class="cell cell-4" x="90" y="0" width="15" height="15" />
              <rect class="cell cell-4" x="150" y="0" width="15" height="15" />
              <rect class="cell cell-3" x="90" y="17" width="15" height="15" />
              <rect class="cell cell-3" x="150" y="17" width="15" height="15" />
              <rect class="cell cell-2" x="90" y="34" width="15" height="15" />
              <rect class="cell cell-2" x="150" y="34" width="15" height="15" />
              <rect class="cell cell-1" x="90" y="51" width="15" height="15" />
              <rect class="cell cell-1" x="150" y="51" width="15" height="15" />
              <rect class="cell cell-1" x="105" y="68" width="15" height="15" />
              <rect class="cell cell-1" x="120" y="68" width="15" height="15" />
              <rect class="cell cell-1" x="135" y="68" width="15" height="15" />
              
              <!-- s -->
              <rect class="cell cell-4" x="180" y="0" width="15" height="15" />
              <rect class="cell cell-3" x="180" y="17" width="15" height="15" />
              <rect class="cell cell-2" x="180" y="34" width="15" height="15" />
              <rect class="cell cell-2" x="195" y="34" width="15" height="15" />
              <rect class="cell cell-2" x="210" y="34" width="15" height="15" />
              <rect class="cell cell-1" x="210" y="51" width="15" height="15" />
              <rect class="cell cell-1" x="180" y="68" width="15" height="15" />
              <rect class="cell cell-1" x="195" y="68" width="15" height="15" />
              <rect class="cell cell-1" x="210" y="68" width="15" height="15" />
              
              <!-- s -->
              <rect class="cell cell-4" x="240" y="0" width="15" height="15" />
              <rect class="cell cell-3" x="240" y="17" width="15" height="15" />
              <rect class="cell cell-2" x="240" y="34" width="15" height="15" />
              <rect class="cell cell-2" x="255" y="34" width="15" height="15" />
              <rect class="cell cell-2" x="270" y="34" width="15" height="15" />
              <rect class="cell cell-1" x="270" y="51" width="15" height="15" />
              <rect class="cell cell-1" x="240" y="68" width="15" height="15" />
              <rect class="cell cell-1" x="255" y="68" width="15" height="15" />
              <rect class="cell cell-1" x="270" y="68" width="15" height="15" />
              
              <!-- e -->
              <rect class="cell cell-4" x="300" y="0" width="15" height="15" />
              <rect class="cell cell-3" x="300" y="17" width="15" height="15" />
              <rect class="cell cell-2" x="300" y="34" width="15" height="15" />
              <rect class="cell cell-2" x="315" y="34" width="15" height="15" />
              <rect class="cell cell-2" x="330" y="34" width="15" height="15" />
              <rect class="cell cell-2" x="345" y="34" width="15" height="15" />
              <rect class="cell cell-2" x="360" y="34" width="15" height="15" />
              <rect class="cell cell-1" x="300" y="51" width="15" height="15" />
              <rect class="cell cell-1" x="300" y="68" width="15" height="15" />
              <rect class="cell cell-1" x="315" y="68" width="15" height="15" />
              <rect class="cell cell-1" x="330" y="68" width="15" height="15" />
              <rect class="cell cell-1" x="345" y="68" width="15" height="15" />
              <rect class="cell cell-1" x="360" y="68" width="15" height="15" />
              
              <!-- i -->
              <rect class="cell cell-4" x="390" y="0" width="15" height="15" />
              <rect class="cell cell-3" x="390" y="17" width="15" height="15" />
              <rect class="cell cell-2" x="390" y="34" width="15" height="15" />
              <rect class="cell cell-1" x="390" y="51" width="15" height="15" />
              <rect class="cell cell-1" x="390" y="68" width="15" height="15" />
              
              <!-- n -->
              <rect class="cell cell-4" x="420" y="0" width="15" height="15" />
              <rect class="cell cell-4" x="480" y="0" width="15" height="15" />
              <rect class="cell cell-3" x="420" y="17" width="15" height="15" />
              <rect class="cell cell-3" x="480" y="17" width="15" height="15" />
              <rect class="cell cell-2" x="420" y="34" width="15" height="15" />
              <rect class="cell cell-2" x="435" y="34" width="15" height="15" />
              <rect class="cell cell-2" x="450" y="34" width="15" height="15" />
              <rect class="cell cell-2" x="465" y="34" width="15" height="15" />
              <rect class="cell cell-2" x="480" y="34" width="15" height="15" />
              <rect class="cell cell-1" x="420" y="51" width="15" height="15" />
              <rect class="cell cell-1" x="480" y="51" width="15" height="15" />
              <rect class="cell cell-1" x="420" y="68" width="15" height="15" />
              <rect class="cell cell-1" x="480" y="68" width="15" height="15" />
              
              <!-- B -->
              <rect class="cell cell-4" x="520" y="0" width="15" height="15" />
              <rect class="cell cell-4" x="535" y="0" width="15" height="15" />
              <rect class="cell cell-4" x="550" y="0" width="15" height="15" />
              <rect class="cell cell-3" x="520" y="17" width="15" height="15" />
              <rect class="cell cell-3" x="565" y="17" width="15" height="15" />
              <rect class="cell cell-2" x="520" y="34" width="15" height="15" />
              <rect class="cell cell-2" x="535" y="34" width="15" height="15" />
              <rect class="cell cell-2" x="550" y="34" width="15" height="15" />
              <rect class="cell cell-1" x="520" y="51" width="15" height="15" />
              <rect class="cell cell-1" x="565" y="51" width="15" height="15" />
              <rect class="cell cell-1" x="520" y="68" width="15" height="15" />
              <rect class="cell cell-1" x="535" y="68" width="15" height="15" />
              <rect class="cell cell-1" x="550" y="68" width="15" height="15" />
              
              <!-- a -->
              <rect class="cell cell-4" x="595" y="0" width="15" height="15" />
              <rect class="cell cell-3" x="595" y="17" width="15" height="15" />
              <rect class="cell cell-2" x="595" y="34" width="15" height="15" />
              <rect class="cell cell-2" x="610" y="34" width="15" height="15" />
              <rect class="cell cell-2" x="625" y="34" width="15" height="15" />
              <rect class="cell cell-1" x="595" y="51" width="15" height="15" />
              <rect class="cell cell-1" x="625" y="51" width="15" height="15" />
              <rect class="cell cell-1" x="595" y="68" width="15" height="15" />
              <rect class="cell cell-1" x="610" y="68" width="15" height="15" />
              <rect class="cell cell-1" x="625" y="68" width="15" height="15" />
              
              <!-- k -->
              <rect class="cell cell-4" x="655" y="0" width="15" height="15" />
              <rect class="cell cell-4" x="700" y="0" width="15" height="15" />
              <rect class="cell cell-3" x="655" y="17" width="15" height="15" />
              <rect class="cell cell-3" x="685" y="17" width="15" height="15" />
              <rect class="cell cell-2" x="655" y="34" width="15" height="15" />
              <rect class="cell cell-2" x="670" y="34" width="15" height="15" />
              <rect class="cell cell-1" x="655" y="51" width="15" height="15" />
              <rect class="cell cell-1" x="685" y="51" width="15" height="15" />
              <rect class="cell cell-1" x="655" y="68" width="15" height="15" />
              <rect class="cell cell-1" x="700" y="68" width="15" height="15" />
              
              <!-- r -->
              <rect class="cell cell-4" x="730" y="0" width="15" height="15" />
              <rect class="cell cell-3" x="730" y="17" width="15" height="15" />
              <rect class="cell cell-2" x="730" y="34" width="15" height="15" />
              <rect class="cell cell-2" x="745" y="34" width="15" height="15" />
              <rect class="cell cell-2" x="760" y="34" width="15" height="15" />
              <rect class="cell cell-1" x="730" y="51" width="15" height="15" />
              <rect class="cell cell-1" x="730" y="68" width="15" height="15" />
              
              <!-- Worm -->
              <circle class="worm" cx="20" cy="20" r="7" />
              <circle class="worm" cx="20" cy="35" r="7" style="animation-delay: 0.1s" />
              <circle class="worm" cx="20" cy="50" r="7" style="animation-delay: 0.2s" />
              <circle class="worm" cx="20" cy="65" r="7" style="animation-delay: 0.3s" />
              <circle class="worm" cx="20" cy="80" r="7" style="animation-delay: 0.4s" />
            </g>
          </svg>
          EOF

      # Add modification to existing snake SVGs (keeping your custom text addition)
      - name: Add custom text to SVGs
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip install beautifulsoup4
          python3 <<EOF
          from bs4 import BeautifulSoup
          import os
          files = [
              'dist/github-contribution-grid-snake.svg',
              'dist/github-contribution-grid-snake-dark.svg'
          ]
          for file_path in files:
              with open(file_path, 'r+') as f:
                  soup = BeautifulSoup(f, 'xml')
                  green_rects = soup.find_all('rect', {'fill': ['#40c463', '#26a641']})
                  
                  for rect in green_rects:
                      x = float(rect['x'])
                      y = float(rect['y'])
                      width = float(rect['width'])
                      height = float(rect['height'])
                      
                      text = soup.new_tag('text')
                      text['x'] = f"{x + width/2}"
                      text['y'] = f"{y + height/2}"
                      text['dominant-baseline'] = "middle"
                      text['text-anchor'] = "middle"
                      text['fill'] = "#ffffff" if rect['fill'] == '#26a641' else "#000000"
                      text['font-size'] = "8"
                      text['font-family'] = "Arial"
                      text.string = "Hussein Bakr"
                      
                      rect.insert_after(text)
                  f.seek(0)
                  f.write(str(soup))
                  f.truncate()
          EOF
      
      # Push SVGs to output branch
      - name: Push SVGs to output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
