name: Generate Snake Image

on:
  schedule:
    - cron: '0 * * * *'  # تحديث الصورة كل ساعة

jobs:
  generate_snake:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pillow

      - name: Run the Python script
        run: python generate_snake.py  # تأكد من أنه اسم الملف صحيح

      - name: Commit and push generated image
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Update snake image'
          add: 'snake_image.png'  # تأكد من اسم الصورة
