name: generate animation

on:
  # شغّل كل يوم عند منتصف الليل
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - master   # أو غيرها لو سمتها main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 10

    steps:
      # لازم تجيب الكونتنتس أولًا
      - name: Checkout repo
        uses: actions/checkout@v3

      # خطوة توليد الـ SVGs – لا تنسى تمرير الـ token هنا
      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # إعادة تسمية ملف الـ dark (مافيش دعم لإزالة ?palette في الـ action)
      - name: Rename dark SVG file
        run: |
          mv "dist/github-contribution-grid-snake-dark.svg?palette=github-dark" \
             dist/github-contribution-grid-snake-dark.svg

      # تثبيت البايثون والـ bs4
      - name: Install Python deps
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pip
          pip3 install beautifulsoup4

      # إضافة النص داخل الـ SVGs
      - name: Add custom text to SVGs
        run: |
          python3 <<EOF
          from bs4 import BeautifulSoup
          files = [
            'dist/github-contribution-grid-snake.svg',
            'dist/github-contribution-grid-snake-dark.svg'
          ]
          for path in files:
              soup = BeautifulSoup(open(path), 'xml')
              green = soup.find_all('rect', fill=['#40c463','#26a641'])
              for r in green:
                  x,y,w,h = map(float, (r['x'], r['y'], r['width'], r['height']))
                  t = soup.new_tag('text', x=str(x+w/2), y=str(y+h/2),
                                   **{'dominant-baseline':'middle','text-anchor':'middle'},
                                   fill= '#ffffff' if r['fill']=='#26a641' else '#000000',
                                   **{'font-size':'8','font-family':'Arial'})
                  t.string = "Hussein Bakr"
                  r.insert_after(t)
              with open(path, 'w') as f: f.write(str(soup))
          EOF

      # ادفع للـ branch اسمه output
      - name: Push SVGs to output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
