name: Contribution Snake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet

      - name: Add Custom Text
        run: |
          # Light Mode
          xmlstarlet ed -L \
            --subnode '//svg' -t elem -n 'text' \
            --var text '$prev' \
            --insert '$text' -t attr -n 'x' -v '50%' \
            --insert '$text' -t attr -n 'y' -v '35' \
            --insert '$text' -t attr -n 'font-family' -v 'Arial' \
            --insert '$text' -t attr -n 'font-size' -v '24' \
            --insert '$text' -t attr -n 'fill' -v '#2F4F4F' \
            --insert '$text' -t attr -n 'text-anchor' -v 'middle' \
            --insert '$text' -t text -v 'Hussein Bakr' \
            dist/snake.svg

          # Dark Mode
          xmlstarlet ed -L \
            --subnode '//svg' -t elem -n 'text' \
            --var text '$prev' \
            --insert '$text' -t attr -n 'x' -v '50%' \
            --insert '$text' -t attr -n 'y' -v '35' \
            --insert '$text' -t attr -n 'font-family' -v 'Arial' \
            --insert '$text' -t attr -n 'font-size' -v '24' \
            --insert '$text' -t attr -n 'fill' -v '#F0F0F0' \
            --insert '$text' -t attr -n 'text-anchor' -v 'middle' \
            --insert '$text' -t text -v 'Hussein Bakr' \
            dist/snake-dark.svg

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
          clean: true
