name: Contribution Snake Generator
on:
  schedule:
    - cron: "0 0 * * *" # يوميًا في منتصف الليل
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Checkout Code
      - uses: actions/checkout@v4

      # 2. Generate Snake (Action مخصصة)
      - uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      # 3. Add Custom Text (Action لمعالجة SVG)
      - uses: actions-hub/svg-manipulator@master
        with:
          files: |
            dist/snake.svg
            dist/snake-dark.svg
          actions: |
            [{
              "type": "add_element",
              "selector": "svg",
              "element": "<text x='50%' y='35' font-family='Arial' font-size='24' fill='#2F4F4F' text-anchor='middle'>Hussein Bakr</text>"
            }]

      # 4. Force Create Directory (Action لإنشاء مجلدات)
      - uses: GuillaumeFalourd/create-folder@v1
        with:
          folders: "dist"
          create-in: "repo"

      # 5. Deploy to GitHub Pages (Action لنشر الملفات)
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
          clean: true
          clean-exclude: |
            *.svg
