name: Generate Snake Animation

on:
  # يعمل تلقائيًا كل 24 ساعة
  schedule:
    - cron: "0 0 * * *"
  
  # يسمح بتشغيل سير العمل يدويًا
  workflow_dispatch:
  
  # يعمل عند كل دفع للفرع الرئيسي
  push:
    branches:
    - main
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # الحصول على محتوى المستودع
      - uses: actions/checkout@v2
      
      # إنشاء رسم الثعبان المتحرك
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: husseinbakr2  # قم بتغيير هذا إلى اسم المستخدم الخاص بك
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      # إنشاء نسخة للوضع الداكن
      - uses: Platane/snk@master
        id: snake-dark
        with:
          github_user_name: husseinbakr2  # قم بتغيير هذا إلى اسم المستخدم الخاص بك
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          snake_color: '#30D050'
          color_snake: '#30D050'
          color_dots: '#DDD,#579543,#62A552,#6DC75B,#85EB6A'
          
      # دفع الملفات المنشأة إلى فرع معين
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
