name: Generate Snake Animation

on:
  # run automatically every 1 hours
  schedule:
    - cron: "0 */1 * * *"
  
  # allows to manually run the workflow
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - main
    - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Checkout the repository content
      - name: Checkout
        uses: actions/checkout@v3

      # Generate the snake animation
      - name: Generate Snake
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          # these next 2 lines generate an SVG with green squares
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          # customizes the color of the snake
          snake_color: '#30D050'

      # Push the generated files to a specific branch
      - name: Push to GitHub Pages branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
