name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */2 * * *"  # تحديث تلقائي كل 2 ساعات
  workflow_dispatch:        # تشغيل يدوي
  push:
    branches:
      - main               # تشغيل عند الدفع لفرع main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # إعطاء صلاحيات الكتابة
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # تنزيل الكود أولاً

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: HusseinBakr2
          show_name: true
          name_color: '#2EFF2E'  # أخضر نيون للاسم
          snake_color: '#4CAF50'  # أخضر زمردي للأفعى
          tile_color: '#708090'   # رمادي فاتح للخلايا
          output: dist/github-contribution-grid-snake.svg

      - name: Create dist directory if missing
        run: mkdir -p dist

      - name: Debug Snake Generation
        run: |
          echo "Listing all files in the workspace:"
          ls -la
          echo "Checking the 'dist' directory:"
          ls -la dist || echo "Directory 'dist' does not exist."

      - name: List files in dist
        run: ls -la dist

      - name: Commit and Push
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          if [ -f dist/github-contribution-grid-snake.svg ]; then
            echo "File found. Committing and pushing changes."
            git add dist/github-contribution-grid-snake.svg
            git commit -m "Update snake animation"
            git push
          else
            echo "File 'dist/github-contribution-grid-snake.svg' not found. Skipping commit."
