name: Generate Snake Animation
on:
  schedule:
    - cron: "0 */2 * * *"  # Auto-update every 2 hours
  workflow_dispatch:        # Manual trigger
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Create directory FIRST
      - name: Create dist directory
        run: mkdir -p dist

      # Now generate snake
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: HusseinBakr2
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and Push
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push
