name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: HusseinBakr2/HusseinBakr2@main
        with:
          github_user_name: HusseinBakr2
          show_name: true
          name_color: 2EFF2E
          snake_color: 4CAF50
          tile_color: 708090
